name: Push changes to Openlayer

on:
  push:
    branches: [main]

jobs:
  openlayer-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Push and test
        env:
          OPENLAYER_API_KEY: ${{ secrets.OPENLAYER_API_KEY }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: python push_to_openlayer.py
